
pod 'AVOSCloud'
pod 'AVOSCloudIM'
pod 'AVOSCloudCrashReporting'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'SVProgressHUD'
pod 'JSBadgeView'
pod 'DateTools' , '~> 1.5.0'
pod 'LZMembersCell'

pod 'AFNetworking', '2.5.4'
pod 'LZAlertViewHelper' , '0.0.2'
pod 'FXForms', '1.2.13'
pod 'iVersion'
pod 'iRate', '1.11.4'
pod 'LeanCloudFeedback', '0.0.7'
pod 'LeanCloudSocial', '0.0.5'
pod 'OpenShare', '0.0.1'
pod 'PopMenu', '2.4'
pod 'SDWebImage'

pod 'FMDB'
pod 'Masonry'

pod 'YYKit'
pod 'HMSegmentedControl'
pod 'Mantle', '~> 2.0.6'
